### ISSUE TITLE
Not working in 2.90, provided console

### ISSUE THREAD

**Issue by Acrivec** [egtwobits/mesh_mesh_align_plus#14]
```
Writing userprefs: 'C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\config\userpref.blend' ok
Traceback (most recent call last):
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_planes.py", line 29, in execute
    item for item in bpy.context.scene.objects if (
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_planes.py", line 30, in <listcomp>
    maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\utils\geom.py", line 4754, in get_select_state
    return item.select
AttributeError: 'Object' object has no attribute 'select'

location: <unknown location>:-1

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_planes.py", line 29, in execute
    item for item in bpy.context.scene.objects if (
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_planes.py", line 30, in <listcomp>
    maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\utils\geom.py", line 4754, in get_select_state
    return item.select
AttributeError: 'Object' object has no attribute 'select'

location: <unknown location>:-1


Traceback (most recent call last):
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_planes.py", line 29, in execute
    item for item in bpy.context.scene.objects if (
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_planes.py", line 30, in <listcomp>
    maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\utils\geom.py", line 4754, in get_select_state
    return item.select
AttributeError: 'Object' object has no attribute 'select'

location: <unknown location>:-1

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_planes.py", line 29, in execute
    item for item in bpy.context.scene.objects if (
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_planes.py", line 30, in <listcomp>
    maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\utils\geom.py", line 4754, in get_select_state
    return item.select
AttributeError: 'Object' object has no attribute 'select'

location: <unknown location>:-1


Traceback (most recent call last):
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_planes.py", line 29, in execute
    item for item in bpy.context.scene.objects if (
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_planes.py", line 30, in <listcomp>
    maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\utils\geom.py", line 4754, in get_select_state
    return item.select
AttributeError: 'Object' object has no attribute 'select'

location: <unknown location>:-1

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_planes.py", line 29, in execute
    item for item in bpy.context.scene.objects if (
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_planes.py", line 30, in <listcomp>
    maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\utils\geom.py", line 4754, in get_select_state
    return item.select
AttributeError: 'Object' object has no attribute 'select'

location: <unknown location>:-1


Traceback (most recent call last):
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_objects.py", line 39, in execute
    for item in bpy.context.scene.objects if maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_objects.py", line 39, in <listcomp>
    for item in bpy.context.scene.objects if maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\utils\geom.py", line 4754, in get_select_state
    return item.select
AttributeError: 'Object' object has no attribute 'select'

location: <unknown location>:-1

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_objects.py", line 39, in execute
    for item in bpy.context.scene.objects if maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_objects.py", line 39, in <listcomp>
    for item in bpy.context.scene.objects if maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\utils\geom.py", line 4754, in get_select_state
    return item.select
AttributeError: 'Object' object has no attribute 'select'

location: <unknown location>:-1


Traceback (most recent call last):
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_lines.py", line 30, in execute
    item for item in bpy.context.scene.objects if (
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_lines.py", line 31, in <listcomp>
    maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\utils\geom.py", line 4754, in get_select_state
    return item.select
AttributeError: 'Object' object has no attribute 'select'

location: <unknown location>:-1

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_lines.py", line 30, in execute
    item for item in bpy.context.scene.objects if (
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_lines.py", line 31, in <listcomp>
    maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\utils\geom.py", line 4754, in get_select_state
    return item.select
AttributeError: 'Object' object has no attribute 'select'

location: <unknown location>:-1


Traceback (most recent call last):
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_lines.py", line 30, in execute
    item for item in bpy.context.scene.objects if (
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_lines.py", line 31, in <listcomp>
    maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\utils\geom.py", line 4754, in get_select_state
    return item.select
AttributeError: 'Object' object has no attribute 'select'

location: <unknown location>:-1

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_lines.py", line 30, in execute
    item for item in bpy.context.scene.objects if (
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_lines.py", line 31, in <listcomp>
    maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\utils\geom.py", line 4754, in get_select_state
    return item.select
AttributeError: 'Object' object has no attribute 'select'

location: <unknown location>:-1
```

**Comment by egtwobits** [comment]
@Acrivec thanks for reporting the issue. I will be taking a look at it sometime soon.

**Comment by egtwobits** [comment]
I think I have it fixed now, will post up an easy to download set of files somewhere soon (it's in the fix_blender_v2_9 branch right now, but that's not easy for most people to use, so wait for the coming uploads if you don't know how to get it from there).

**Comment by egtwobits** [comment]
See if this works for you, I'll draft a release if so:

[mesh_mesh_align_plus.zip](https://github.com/egtwobits/mesh_mesh_align_plus/files/5038381/mesh_mesh_align_plus.zip)

**Comment by Acrivec** [comment]
```Traceback (most recent call last):
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_planes.py", line 29, in execute
    item for item in bpy.context.scene.objects if (
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_planes.py", line 30, in <listcomp>
    maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\utils\geom.py", line 4754, in get_select_state
    return item.select
AttributeError: 'Object' object has no attribute 'select'

location: <unknown location>:-1

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_planes.py", line 29, in execute
    item for item in bpy.context.scene.objects if (
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_planes.py", line 30, in <listcomp>
    maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\utils\geom.py", line 4754, in get_select_state
    return item.select
AttributeError: 'Object' object has no attribute 'select'

location: <unknown location>:-1


Traceback (most recent call last):
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_planes.py", line 29, in execute
    item for item in bpy.context.scene.objects if (
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_planes.py", line 30, in <listcomp>
    maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\utils\geom.py", line 4754, in get_select_state
    return item.select
AttributeError: 'Object' object has no attribute 'select'

location: <unknown location>:-1

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_planes.py", line 29, in execute
    item for item in bpy.context.scene.objects if (
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_planes.py", line 30, in <listcomp>
    maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\utils\geom.py", line 4754, in get_select_state
    return item.select
AttributeError: 'Object' object has no attribute 'select'

location: <unknown location>:-1


Traceback (most recent call last):
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_objects.py", line 39, in execute
    for item in bpy.context.scene.objects if maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_objects.py", line 39, in <listcomp>
    for item in bpy.context.scene.objects if maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\utils\geom.py", line 4754, in get_select_state
    return item.select
AttributeError: 'Object' object has no attribute 'select'

location: <unknown location>:-1

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_objects.py", line 39, in execute
    for item in bpy.context.scene.objects if maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_objects.py", line 39, in <listcomp>
    for item in bpy.context.scene.objects if maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\utils\geom.py", line 4754, in get_select_state
    return item.select
AttributeError: 'Object' object has no attribute 'select'

location: <unknown location>:-1


Traceback (most recent call last):
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_points.py", line 30, in execute
    item for item in bpy.context.scene.objects if (
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_points.py", line 31, in <listcomp>
    maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\utils\geom.py", line 4754, in get_select_state
    return item.select
AttributeError: 'Object' object has no attribute 'select'

location: <unknown location>:-1

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_points.py", line 30, in execute
    item for item in bpy.context.scene.objects if (
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_points.py", line 31, in <listcomp>
    maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\utils\geom.py", line 4754, in get_select_state
    return item.select
AttributeError: 'Object' object has no attribute 'select'

location: <unknown location>:-1


Traceback (most recent call last):
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_points.py", line 30, in execute
    item for item in bpy.context.scene.objects if (
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_points.py", line 31, in <listcomp>
    maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\utils\geom.py", line 4754, in get_select_state
    return item.select
AttributeError: 'Object' object has no attribute 'select'

location: <unknown location>:-1

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_points.py", line 30, in execute
    item for item in bpy.context.scene.objects if (
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_points.py", line 31, in <listcomp>
    maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\utils\geom.py", line 4754, in get_select_state
    return item.select
AttributeError: 'Object' object has no attribute 'select'

location: <unknown location>:-1


Traceback (most recent call last):
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_points.py", line 30, in execute
    item for item in bpy.context.scene.objects if (
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_points.py", line 31, in <listcomp>
    maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\utils\geom.py", line 4754, in get_select_state
    return item.select
AttributeError: 'Object' object has no attribute 'select'

location: <unknown location>:-1

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_points.py", line 30, in execute
    item for item in bpy.context.scene.objects if (
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_points.py", line 31, in <listcomp>
    maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\utils\geom.py", line 4754, in get_select_state
    return item.select
AttributeError: 'Object' object has no attribute 'select'

location: <unknown location>:-1


Traceback (most recent call last):
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_points.py", line 30, in execute
    item for item in bpy.context.scene.objects if (
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_points.py", line 31, in <listcomp>
    maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\utils\geom.py", line 4754, in get_select_state
    return item.select
AttributeError: 'Object' object has no attribute 'select'

location: <unknown location>:-1

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_points.py", line 30, in execute
    item for item in bpy.context.scene.objects if (
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\align_points.py", line 31, in <listcomp>
    maplus_geom.get_select_state(item)
  File "C:\Users\Acrivec\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\mesh_mesh_align_plus\utils\geom.py", line 4754, in get_select_state
    return item.select
AttributeError: 'Object' object has no attribute 'select'

location: <unknown location>:-1
```

To be sure I'm doing it right - first I enter edit mode of destignation, select the plane/face (points?), grab destignation, then escape edit mode, go to object I want to adjust, enter edit mode - select plane I want to adjust, exit edit mode, and hit apply?

**Comment by egtwobits** [comment]
I think you might need to delete/uninstall the old one? Does the version say 0.6.1 in the addon info section in the preferences?

**Comment by egtwobits** [comment]
Also yes, your steps/description are correct.

**Comment by egtwobits** [comment]
UMMMMMM, I think I may have uploaded the wrong file by mistake. Stand by...

**Comment by egtwobits** [comment]
Yes I think I uploaded the wrong file, sorry about that. Try this one: 
[mesh_mesh_align_plus.zip](https://github.com/egtwobits/mesh_mesh_align_plus/files/5038447/mesh_mesh_align_plus.zip)

**Comment by Acrivec** [comment]
Had some errors at first, but restarted blender and it worked on second try. Thanks. ;)

**Comment by egtwobits** [comment]
Thanks for reporting this. It was caused by some old code, back when I tried to keep the add-on compatible with both 2.7x and 2.8x (that idea was axed), then they changed the versioning scheme for Blender. Things should be pretty stable from here.

Here's a new release for this, check the releases page: https://github.com/egtwobits/mesh_mesh_align_plus/releases
